version: '3.1'

services:

  db:
    image: postgres
    hostname: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - 9000:8080

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@eample.com
      - PGADMIN_DEFAULT_PASSWORD=example
    ports:
      - 80:80
