version: '3.1'

services:

  db:
    image: postgres
    hostname: db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    hostname: adminer
    restart: always
    ports:
      - 9000:8080
